### ISSUE TITLE
Future: Handling a monitor channel

### ISSUE THREAD

**Issue by tritemio** [Photon-HDF5/photon-hdf5#15]
# Summary

Some measurement have one or more extra detection channels used to monitor the laser power. Currently these extra `timestamps` are saved in the same `timestamps` array. The array `detectors` contains a different ID (a number) for each detetctor and allow to separate them out.

In the future these monitor channels can be present in a multi-spot setup. In this case is not natural having the monitor timestamps in one of the spot-specific `photon_data` groups.

Finally some measurements have bogous (spurious) channels (very low in count) that should be ignored.
# Question 1

Should we "warn" the user that the file contains those extra photons? Or we should just provide as "best practice" guideline telling the user to always check which unique values are in `detectors`?
# Question 2

 How do we handle the multi-spot case?
# Question 3

`/setup/num_pixels` should include also the monitor-channel detectors or only the emission-channel ones?

**Comment by tritemio** [comment]
# Answer Q1 & Q2

## Option 1

### Single-spot

Use the [`labels` table](http://photon-hdf5.readthedocs.org/en/latest/phdata.html#detectors-specs) in `/photon_data/measurements_spec/detectors_specs/`

The table can read something like

| Detector ID | Label |
| --- | --- |
| 0 | donor |
| 1 | acceptor |
| 2 | monitor total excitation power |
| 3 | spurious timestamps due to acquisition artifacts |

By looking at this table the user immediately know if there are "extra" channels and what they are.

### Multi-spot

Use a user (custom) photon_data group that contains only monitor channels. One (or two) additional measurement_specs can be created to handle the case of 1 (or 2) monitor channels.

## Option 2

Use a user (custom) photon_data group for both single and multi-spot.

## Option 3

Add variation of each `measurement_type` by adding `_plus_monitor`. Each of these variations should handle both 1 and 2 monitor channel cases.

The multi-spot case can be handled via a custom photon_data group.

**Comment by smXplorer** [comment]
Option 3 seems preferable.

**Comment by tritemio** [comment]
In 0.5 we have channel labels and number of counts per detector. See #33.

I mark this issue solved for the purpose of v0.5. Discussion can be resumed in the future if needed.
