### ISSUE TITLE
ALEX alternation period definitions

### ISSUE THREAD

**Issue by tritemio** [Photon-HDF5/photon-hdf5#16]
I found an inconsistency in the definition of the alternation period range in the ALEX histograms for donor and acceptor.

Currently (v0.3), these ranges are named:

`alex_period_spectral_ch1`
`alex_period_spectral_ch2`

By `spectral_ch1/2` in the format we indicate the detection channels (resp. donor and acceptor). The previous naming is inconsistent (logically wrong!) because each of these periods refer to one **excitation** laser, not to one detection channel.

These names are present in both us-ALEX and ns-ALEX measurement types. 

Let's discuss if we need to change them (probably yes) and which new names we should use.

**Comment by tritemio** [comment]
# Proposal 1

`alex_period`
`alex_period_excitation1`
`alex_period_excitation2`

# Proposal 2

`alex_period`
`alex_period_range_excitation1`
`alex_period_range_excitation2`

**Comment by tritemio** [comment]
FYI, the original documentation (0.3) is:
- http://photon-hdf5.readthedocs.org/en/version0.3/phdata.html#measurement-specs

and the new "tentative" docs using **Proposal 1** can be found here:
- http://photon-hdf5.readthedocs.org/en/latest/phdata.html#measurement-specs

The changes in the document (the diff) can bee read [here](https://github.com/Photon-HDF5/photon-hdf5/commit/f6431b11caccc8cb11e85e55676df848207e99e4?short_path=3459584#diff-34595842989a846a08c7e08840991436).

**Comment by tritemio** [comment]
# Proposal 3

`alex_period`
`alex_excitation_range1`
`alex_excitation_range2`

# Proposal 4

`alex_period`
`alex_excitation1`
`alex_excitation2`

**Comment by smXplorer** [comment]
I am glad to see that we agree that the only thing we can define for a photon is the excitation period it falls in (at least in ns ALEX; this is less of an issue for us ALEX and dyes with ns lifetime. But just think for a second of emitters with tens or hundreds of us lifetimes...)
alex_excitation_period1, etc would seem to me a logical name.

Also note that the custom name for the inverse of a laser period is laser repetition rate, not laser pulse rate.

**Comment by tritemio** [comment]
# Proposal 5

`alex_period`
`alex_excitation_period1`
`alex_excitation_period2`

**Comment by tritemio** [comment]
@smXplorer, are you proposing to rename `laser_pulse_rate` to `laser_repetition_rate`? Both of them are unambiguous for me.

**Comment by smXplorer** [comment]
yes. it is just that usage favors laser repetition rate.

**Comment by tritemio** [comment]
I think the best options are Proposals 1 and 5.

In general I tend to prefer a name that goes from general to particular (like in programming languages) compared to "english language" order. It seems to me more logical. 

So, I vote Proposal 1. @smXplorer votes proposal 5. @talaurence which one do you prefer?

**Comment by talaurence** [comment]
I vote Proposal 1 as well.  It looks strange on first glance, but when you read the documentation it makes more sense than Proposal 5.... at least to me.

**Comment by tritemio** [comment]
@talaurence ok thanks, in case you wonder, right now phconvert 0.5 uses proposal 1, while phconvert 0.5.1 uses proposal 5.

@smXplorer, do you want to have a final word?

Regarding `laser_pulse_rate` vs `laser_repetition_rate` I'm absolutely ok with both, so since @smXplorer  prefere the second I'll change it this way.

**Comment by talaurence** [comment]
It is actually OK either way - if @smXplorer likes it better, we don't have to go back to proposal 1

**Comment by smXplorer** [comment]
I am fine with option 1.

**Comment by tritemio** [comment]
Ok, it turns out to be equivalent so I stick to the latest implementation in phconvert 0.5.1 that is

`alex_excitation_period1`
`alex_excitation_period2`
`laser_repetition_rate`

I'll close the issue shortly, once I finish to update the docs.
