### ISSUE TITLE
Add fields for SPAD arrays

### ISSUE THREAD

**Issue by tritemio** [Photon-HDF5/photon-hdf5#18]
When using SPAD (or other) arrays would be useful to specify the **number of array modules** used in the measurement. Currently we only save **num_pixels** which is the total number of pixels (see [specs](http://photon-hdf5.readthedocs.org/en/latest/phdata.html#setup-group)).

Also, it would be useful to save the "position" on the chip for each pixel. For 1-D SPAD array this can be a 1-D numerical array containing detector ID for each position. For 2-D arrays, it can be a 2-D numerical array.

**Comment by smXplorer** [comment]
If you use a 1D array of I64, you can easily account for a 2D detector matrix by using the lowest word for X, highest for Y. If you need X, Y and Z, the same principle can apply (e.g. 20 bits per dimension). The only open question with this approach is how to describe the encoding used.

**Comment by tritemio** [comment]
No need to encode it in a int64. We can just use a 2-column array, first column for X, second for Y. But you are talking about [detector ID](http://photon-hdf5.readthedocs.org/en/latest/phdata.html#detector-ids), that is already in the specs (it can be specified better).

I was thinking a general mapping (a single 2D array for each detector) mapping IDs to a position. In this way we don't necessarily need to use 2-tuple detector IDs for 2D arrays.

**Comment by tritemio** [comment]
Addressed in #33 with the optional field `/setup/detectors/module`.
