### ISSUE TITLE
nanotimes and time_reversed flag

### ISSUE THREAD

**Issue by tritemio** [Photon-HDF5/photon-hdf5#22]
In `nanotimes_specs` there is the flag `time_reversed` that says where the time axis orientation of  `nanotimes` array is reversed or not.

This is redundant. Would be better to always use the convention that time axis is not reversed and eliminate the `time_reversed` flag.

There is a conceptually different information that we may want to save: whether the TCSPC setup have start-stop inverted (start with photon, stop with laser sync) as customary, or not.

It seems to me that this information is not useful. Also saving this would 100% rely on the user setting the correct value at conversion file.

I propose to don't add any additional flag for this field for now. It can always added later if the need arise. Conversely, if we add the flag we have to keep it forever to assure backward compatibility.

@smXplorer, @talaurence  do you agree with the proposed changes (removing `time_reversed`)?

**Comment by smXplorer** [comment]
Sure, as long as it is clearly prescribed that photon-hdf5 ns-ALEX files needs to have nanotimes saved in such a way that lifetime decay histograms have the proper orientation.

**Comment by tritemio** [comment]
I will add a note to the docs.
