### ISSUE TITLE
list of detector ID

### ISSUE THREAD

**Issue by smXplorer** [Photon-HDF5/photon-hdf5#24]
What is the expected format of a detector list (e.g. for spectral_chx)?
[0, 1, 2]?
This should be added to the documentation.

**Comment by tritemio** [comment]
In the specs:

http://photon-hdf5.readthedocs.org/en/latest/phdata.html#detectors-specs

last paragraph is the info you are looking for.

**Comment by smXplorer** [comment]
Last paragraph reads:

All previous fields are arrays containing one or more Detector pixel IDs. For example, a 2-color smFRET measurement will have only one value in spectral_ch1 (donor) and one value in spectral_ch2 (acceptor). A 2-color smFRET measurement with polarization (4 detectors) will have 2 values in each of the spectral_chX and polarization_chX fields (where X=1 or 2). For a multispot smFRET measurement, spectral_chX will contain the list of donor/acceptor pixels (see Multi-spot measurements).

Where is my question addressed?

**Comment by tritemio** [comment]
What information is not clear? Among the possible HDF5 dataset types, all detector specs are arrays even when they contain a single element. If this is not what you ask please clarify.

**Comment by smXplorer** [comment]
My bad, I was looking for the format of the detector list in the yaml file.

**Comment by tritemio** [comment]
Ok, yes, detectors_specs are lists in YAML. A list in YAML can either have to the compact form:

```
[item1, item2, item3]
```

or the expanded form:

```
- item1
- item2
- item3
```

The [YAML entry on Wikipedia](https://en.wikipedia.org/wiki/YAML#Language_elements) has a nice summary on the YAML format.
