### ISSUE TITLE
Number of timestamps per detector

### ISSUE THREAD

**Issue by smXplorer** [Photon-HDF5/photon-hdf5#30]
For file preview, it would be helpful to have information on the number of timestamps per detector (in the photon_data group). Right now, this requires loading the detector array, and counting the occurrence of each pixelID. This is time and resource consuming and not really compatible with a "preview" action.
A possible application would be to not bother with looking further into channels with very low counts.

**Comment by tritemio** [comment]
We can do it but requires bumping up Photon-HDF5 version number.

**Comment by tritemio** [comment]
Addressed by #33 with the new /setup/detectors/counts field.
