### ISSUE TITLE
Handling of dead pixels

### ISSUE THREAD

**Issue by smXplorer** [Photon-HDF5/photon-hdf5#31]
For multispot experiments, it would be helpful to know about "dead" detectors (those which do not output timestamps, but are part of the detector). In practice, it is of course possible to give pixels pixelIDs which provide this information (for instance, if pixel 3 of a series 1, 2, ... 16, is dead, the remaining pixels can be given pixelIDs: 1, 2, 4, , ..., 16).
In other words, I think having spots with empty timestamps and detectors arrays, but non-empty detector specs, should be possible.
It is possible in the current format, but the documentation does not discuss this at all and therefore there is an ambiguity that could lead to confusion and problems in the future.

**Comment by tritemio** [comment]
Note: I experienced incompatibilities issues with using empty arrays.

**Comment by smXplorer** [comment]
If the number of timestamps for each pixelID is provided (see another suggestion), this shouldn't be a problem.

**Comment by tritemio** [comment]
Closing. This is addressed by the new field  `/setup/detectors/counts`. See #33.
