### ISSUE TITLE
Add detector labels

### ISSUE THREAD

**Issue by tritemio** [Photon-HDF5/photon-hdf5#5]
Add a table in `detectors_specs` with 2 columns: detector ID and label (a string).

Possible name:

`detector_labels`

**Comment by smXplorer** [comment]
Allowing pixel labels would help preserving original information (such as explicit names provided by users). For instance, "Ch 1" , "Ch 2" or "Donor-s", "Donor-p", etc.

**Comment by tritemio** [comment]
Addressed by #33 using `/setup/detectors/label`.
